# Generated by Django 5.0 on 2023-12-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcenter',
            old_name='name',
            new_name='healthcenter_name',
        ),
    ]
