# Generated by Django 5.0 on 2023-12-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dts', '0002_rename_name_healthcenter_healthcenter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('DrugID', models.AutoField(primary_key=True, serialize=False)),
                ('DrugName', models.CharField(max_length=255)),
                ('BatchNumber', models.CharField(max_length=50)),
                ('ManufacturingDate', models.DateTimeField(auto_now_add=True)),
                ('ExpirationDate', models.DateTimeField()),
                ('QuantityProduced', models.PositiveIntegerField()),
                ('CurrentLocation', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='pharmaceuticals',
        ),
    ]
