# Generated by Django 5.0 on 2023-12-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dts', '0003_drug_delete_pharmaceuticals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='QuantityProduced',
            new_name='Quantity',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='CurrentLocation',
        ),
    ]
