# Generated by Django 5.0 on 2023-12-26 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dts', '0004_rename_quantityproduced_drug_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='DrugDescription',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
