# Generated by Django 5.0 on 2023-12-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dts', '0005_drug_drugdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('UserType', models.CharField(max_length=50)),
                ('Phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
